services:
  express-app-1:
    build: .
    container_name: express-app-1
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm start
    networks:
      - url_shortener_net


networks:
  url_shortener_net:
    external: true
