services:
  primary:
    image: postgres:15
    container_name: pg-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg-primary-data:/var/lib/postgresql/data
      - pg-primary-archive:/var/lib/postgresql/archive
      - ./primary/init:/docker-entrypoint-initdb.d
    networks:
      - pg-net
    ports:
      - "5433:5432"

  standby:
    image: postgres:15
    container_name: pg-standby
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - primary
    volumes:
      - pg-standby-data:/var/lib/postgresql/data
      - ./standby/init:/docker-entrypoint-initdb.d
      # - ./standby/init:/init
    networks:
      - pg-net
    ports:
      - "5434:5432"

  pgpool:
    image: bitnami/pgpool:4
    container_name: pg-pgpool
    environment:
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin
      - PGPOOL_BACKEND_NODES=0:pg-primary:5432,1:pg-standby:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_NUM_INIT_CHILDREN=32
      - PGPOOL_HEALTH_CHECK_PERIOD=10
    ports:
      - "5432:5432"
    networks:
      - pg-net
    depends_on:
      - primary
      - standby

volumes:
  pg-primary-data:
  pg-primary-archive:
  pg-standby-data:

networks:
  pg-net:
