version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data:/root/redis"
    command: [
      "redis-server",
      "--requirepass", "admin",
      "--maxmemory", "256mb", 
      "--maxmemory-policy", "allkeys-lru",
    ]
    restart: unless-stopped 